### ISSUE TITLE
Cant rebuild apk if iglogger.smali present

### ISSUE THREAD

**Issue by srikrishnacj** [intrepidusgroup/IGLogger#3]
I am unable to build apk with IGLogger. I am getting the folloing error when i tryed to build apk. both APKStudio and Ten Studio failed to build apk.

I: Using Apktool 2.0.0-Beta9 on b

I: Smaling...

....\Lab\b\smali\iglogger.smali[50,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[50,15] mismatched input '"s"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[117,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[117,15] mismatched input '"data"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[214,15] no viable alternative at input 't'

....\Lab\b\smali\iglogger.smali[214,17] no viable alternative at input 'Ljava/lang/Throwable;'

....\Lab\b\smali\iglogger.smali[250,15] no viable alternative at input 'logtag'

....\Lab\b\smali\iglogger.smali[250,22] no viable alternative at input 'Ljava/lang/String;'

....\Lab\b\smali\iglogger.smali[326,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[326,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[387,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[387,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[452,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[452,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[513,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[513,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[574,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[574,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[641,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[641,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[708,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[708,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[773,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[773,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[849,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[849,15] mismatched input '"m"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[910,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[911,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[910,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[928,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[929,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[928,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[950,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[951,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[950,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[968,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[969,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[968,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[986,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[987,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[986,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1010,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1011,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1010,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1034,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1035,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1034,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1056,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1057,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1056,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1091,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1092,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1091,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1109,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1110,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1109,15] mismatched input '"logtag"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1127,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1128,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1127,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1162,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1163,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1162,15] mismatched input '"logtag"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1293,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1294,4] Error for input '.parameter': Invalid directive

....\Lab\b\smali\iglogger.smali[1293,15] mismatched input '"t"' expecting END_METHOD_DIRECTIVE

....\Lab\b\smali\iglogger.smali[1306,4] missing EOF at '.prologue'

Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: iglogger.smali

```
at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:72)

at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:56)

at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)

at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:338)

at brut.androlib.Androlib.buildSources(Androlib.java:299)

at brut.androlib.Androlib.build(Androlib.java:285)

at brut.androlib.Androlib.build(Androlib.java:258)

at brut.apktool.Main.cmdBuild(Main.java:236)

at brut.apktool.Main.main(Main.java:88)
```

**Comment by AnthonyDiPerna** [comment]
You need to rebuild iglogger.java into a .apk file then decompile it with apktool to get an updated iglogger.smali.

**Comment by regs3** [comment]
Hi!
I ran into the same issue. Could you write it in details, how can I compile the java into smali?

Thanks.

**Comment by bcaller** [comment]
You can use the fork https://github.com/b3nn/IGLogger or just make an apk in Android studio which includes IGLogger. Then use apktool to get the smali.

**Comment by OmarElmekaalel** [comment]
hello!!
when i want to recompile my apk i have this probleme could u help me plz  
this is my email adress plz 
mehdi.vvm@gmail.com
..\3-Out\PandaRun.apk\smali\com\adventure\panda\runner\BuildConfig.smali[1,24] Error for input '.jabo': Invalid directive
..\3-Out\PandaRun.apk\smali\com\adventure\panda\runner\BuildConfig.smali[1,29] Error for input '.pictu': Invalid directive
..\3-Out\PandaRun.apk\smali\com\adventure\panda\runner\BuildConfig.smali[1,35] Error for input '.arob': Invalid directive
..\3-Out\PandaRun.apk\smali\com\adventure\panda\runner\BuildConfig.smali[1,40] Error for input '/': Invalid text
..\3-Out\PandaRun.apk\smali\com\adventure\panda\runner\BuildConfig.smali[1,20] mismatched input 'Lcom' expecting CLASS_DESCRIPTOR
..\3-Out\PandaRun.apk\smali\com\adventure\panda\runner\BuildConfig.smali[1,52] Error for input ';': Invalid text
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com/adventure/panda/runner/BuildConfig.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:412)
	at brut.androlib.Androlib.buildSources(Androlib.java:343)
	at brut.androlib.Androlib.build(Androlib.java:299)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
